### PR TITLE
add grade assessment modal

### PR DESCRIPTION
**Pull request by SanCampos**
The `.html` file had to be renamed to `test-modal` due to a bug resulting in non-loading of the `CSS` file.

### CODE REVIEW

**Comment by daniddelrio** [comment]
Hi Santi! Really nice job so far. Just a few minor comments:

1. To play it safe, let's not change the background of the whole `<body>` tag! We might just use one HTML and CSS file for the whole website so might be better to just change the background on a per-<div> basis. Also, acc to Figma the background color of the modal is #DCDCDC.
2. The grade for when you input in the Letter Grade field is too much to the left. Give some margin or padding to it so that there's space within it. 
Screen Shot 2020-05-19 at 10 13 55 PM
3. The "Numerical Result" exceeds the width of the field! Maybe make the boxes a bit bigger?
Screen Shot 2020-05-19 at 10 14 18 PM

**Comment by daniddelrio** [comment]
Also! Put your files into one folder called "Campos" to organize the files for now

**Comment by SanCampos** [comment]
> 
> 
> Hi Santi! Really nice job so far. Just a few minor comments:
> 
>     1. To play it safe, let's not change the background of the whole `<body>` tag! We might just use one HTML and CSS file for the whole website so might be better to just change the background on a per- basis. Also, acc to Figma the background color of the modal is #DCDCDC.
> 
>     2. The grade for when you input in the Letter Grade field is too much to the left. Give some margin or padding to it so that there's space within it.
> 
> 
> Screen Shot 2020-05-19 at 10 13 55 PM
> 3. The "Numerical Result" exceeds the width of the field! Maybe make the boxes a bit bigger?
> 
> Screen Shot 2020-05-19 at 10 14 18 PM

For number 2, can I get information on what browser you are using to view the modal? The grade is centered on my machine.

**Comment by daniddelrio** [comment]
> For number 2, can I get information on what browser you are using to view the modal? The grade is centered on my machine.

I'm using Chrome on my Macbook! When I checked Inspect Element on Chrome, it has something to do with this CSS code:
Screen Shot 2020-05-28 at 4 34 04 PM

May I ask what this does? Also, bumping you to move your files into one folder called "Campos" hehe

Lastly, kindly add this to your `<head>`:
```
<meta name="viewport" content="width=device-width, initial-scale=1" >
```

Helps with responsiveness. Thanks Santino!

**Pull request merged**
